name: Android Build and Upload to Google Drive

on:
  push:
    branches:
      - main

jobs:
  build_and_upload:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'temurin'

      - name: Install Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable

      - name: Clear Gradle Cache
        run: rm -rf ~/.gradle/caches/

      - name: Build APK
        working-directory: android
        run: |
          ./gradlew clean assembleRelease

      - name: Install gdrive CLI
        run: |
          sudo apt-get install -y unzip
          curl -L -o gdrive.zip https://github.com/prasmussen/gdrive/releases/download/2.1.0/gdrive-linux-x64
          unzip gdrive.zip -d /usr/local/bin
          chmod +x /usr/local/bin/gdrive

      - name: Upload APK to Google Drive
        env:
          GDRIVE_ACCESS_TOKEN: ${{ secrets.GDRIVE_ACCESS_TOKEN }}
        working-directory: android
        run: |
          ./gradlew clean assembleRelease
          APK_PATH=$(find app/build/outputs/apk/release -name "*.apk" | head -n 1)
          gdrive upload --parent <FOLDER_ID> "$APK_PATH"
