name: Android Fastlane with Firebase App Distribution Workflow

on:
  push:
    branches:
      - main

jobs:
  distribute_to_firebase:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout my repo code
        uses: actions/checkout@v2

      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'temurin'

      - name: Install Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable
      - name: Clear Gradle Cache
        run: rm -rf ~/.gradle/caches/

      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: "3.2.3"
          bundler-cache: true
          working-directory: android

      - name: Build APK with Verbose Logs
        run: flutter build apk --release -v

      - name: Build and Distribute APK
        env:
          FIREBASE_CLI_TOKEN: ${{ secrets.FIREBASE_CLI_TOKEN }}
        working-directory: android
        run: |
          bundle exec fastlane android firebase_distribution